import { defineSeed } from '@pro-laico/payload-seed'

export default defineSeed('images', ({ file, ref }) => [
  {
    _key: 'hero',
    _file: file('hero.jpg'),
    alt: 'A modern timber-and-concrete home at dusk',
    focalX: 50,
    focalY: 55,
    folder: ref('payload-folders', 'site'),
  },
  {
    _key: 'svc-architecture',
    _file: file('svc-architecture.png'),
    alt: 'Board-formed concrete and timber facade',
    focalX: 50,
    focalY: 50,
    folder: ref('payload-folders', 'services'),
  },
  {
    _key: 'svc-interiors',
    _file: file('svc-interiors.png'),
    alt: 'A warm minimalist living room',
    focalX: 50,
    focalY: 50,
    folder: ref('payload-folders', 'services'),
  },
  {
    _key: 'svc-landscape',
    _file: file('svc-landscape.png'),
    alt: 'A landscaped garden with a stone path',
    focalX: 50,
    focalY: 60,
    folder: ref('payload-folders', 'services'),
  },
  {
    _key: 'svc-renovation',
    _file: file('svc-renovation.png'),
    alt: 'A renovated kitchen with restored brick',
    focalX: 50,
    focalY: 50,
    folder: ref('payload-folders', 'services'),
  },
  {
    _key: 'cedar-hill',
    _file: file('cedar-hill.jpg'),
    alt: 'Cedar Hill Residence at dusk',
    focalX: 50,
    focalY: 50,
    folder: ref('payload-folders', 'projects'),
  },
  {
    _key: 'cedar-hill-interior',
    _file: file('cedar-hill-interior.png'),
    alt: 'The double-height living space at Cedar Hill',
    focalX: 50,
    focalY: 45,
    folder: ref('payload-folders', 'projects'),
  },
  {
    _key: 'foundry-loft',
    _file: file('foundry-loft.jpg'),
    alt: 'The Foundry Loft interior',
    focalX: 50,
    focalY: 50,
    folder: ref('payload-folders', 'projects'),
  },
  {
    _key: 'foundry-detail',
    _file: file('foundry-detail.png'),
    alt: 'Blackened steel kitchen detail at The Foundry',
    focalX: 50,
    focalY: 50,
    folder: ref('payload-folders', 'projects'),
  },
  {
    _key: 'riverside-pavilion',
    _file: file('riverside-pavilion.jpg'),
    alt: 'Riverside Pavilion by the water',
    focalX: 50,
    focalY: 55,
    folder: ref('payload-folders', 'projects'),
  },
  {
    _key: 'riverside-interior',
    _file: file('riverside-interior.png'),
    alt: 'Inside the Riverside Pavilion',
    focalX: 50,
    focalY: 50,
    folder: ref('payload-folders', 'projects'),
  },
  {
    _key: 'team-1',
    _file: file('team-1.png'),
    alt: 'Portrait of the principal architect',
    focalX: 50,
    focalY: 38,
    folder: ref('payload-folders', 'team'),
  },
  {
    _key: 'team-2',
    _file: file('team-2.png'),
    alt: 'Portrait of the design director',
    focalX: 50,
    focalY: 38,
    folder: ref('payload-folders', 'team'),
  },
  {
    _key: 'team-3',
    _file: file('team-3.png'),
    alt: 'Portrait of the landscape lead',
    focalX: 50,
    focalY: 38,
    folder: ref('payload-folders', 'team'),
  },
])
