import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, isAbsolute, join, relative, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { glob } from 'tinyglobby'
import { asset, ref } from './refs'
import type { SeedDefinition } from './types'

const DEFAULT_DISCOVER = ['**/seed.ts', '**/seed/**/*.ts']
// Exclude runner scripts (e.g. `scripts/seed.ts`) — they match `**/seed.ts` but are CLI
// entries with import side effects, not `defineSeed` modules.
const IGNORE = ['**/node_modules/**', '**/dist/**', '**/.next/**', '**/.turbo/**', '**/.source/**', '**/scripts/**']
const DEFAULT_PKG = '@pro-laico/payload-seed'
const tokens = { ref, asset }

export interface GenerateOptions {
  /** Project root to scan + resolve `out` against. Default: `process.cwd()`. */
  cwd?: string
  /** Discovery globs. Default: `['**\/seed.ts', '**\/seed/**\/*.ts']`. */
  discover?: string[]
  /** Output file (relative to cwd unless absolute). Default: `src/seed.generated.ts`. */
  out?: string
  /** Emit a `definitions` barrel (static imports) for bundled servers. Default: true. */
  barrel?: boolean
  /** Module to augment. Default: `@pro-laico/payload-seed`. */
  packageName?: string
}

export interface GenerateResult {
  out: string
  collections: Record<string, string[]>
  globals: string[]
  assets: string[]
  /** Number of seed definition files included. */
  files: number
}

interface Discovered {
  file: string
  def: SeedDefinition
}

function isSeedDefinition(value: unknown): value is SeedDefinition {
  return (
    typeof value === 'object' &&
    value !== null &&
    'kind' in value &&
    ['collection', 'global', 'block', 'assets'].includes((value as { kind: string }).kind)
  )
}

async function discoverWithPaths(globs: string[], cwd: string, ignore: string[]): Promise<Discovered[]> {
  const files = await glob(globs, { cwd, absolute: true, ignore })
  const out: Discovered[] = []
  for (const file of files.sort()) {
    let mod: { default?: unknown }
    try {
      mod = (await import(pathToFileURL(file).href)) as { default?: unknown }
    } catch {
      continue
    }
    if (isSeedDefinition(mod.default)) out.push({ file, def: mod.default })
  }
  return out
}

/** Relative import specifier from `fromDir` to `file`, POSIX-style and extension-less. */
function importSpecifier(fromDir: string, file: string): string {
  let rel = relative(fromDir, file)
    .replace(/\\/g, '/')
    .replace(/\.tsx?$/, '')
  if (!rel.startsWith('.')) rel = `./${rel}`
  return rel
}

const union = (values: string[]): string => (values.length ? values.map((v) => `'${v}'`).join(' | ') : 'never')

/**
 * Scan the seed files and write the generated module: a `SeedRegistry` augmentation (so
 * `ref()`/`asset()` keys are type-checked against the declared `_key`s — remove an item
 * and every reference to it errors) and, optionally, a `definitions` barrel of static
 * imports for runtimes that can't auto-discover (a bundled server).
 *
 * Keys are read by importing the seed definitions and reading their actual data — the same
 * mechanism the engine uses — so the types always match what gets seeded. Run it after
 * changing any `_key`, global, or asset key (mirrors `payload generate:types`).
 */
export async function generateSeedTypes(options: GenerateOptions = {}): Promise<GenerateResult> {
  const cwd = options.cwd ? resolve(options.cwd) : process.cwd()
  const outRel = options.out ?? 'src/seed.generated.ts'
  const outAbs = isAbsolute(outRel) ? outRel : join(cwd, outRel)
  const barrel = options.barrel ?? true
  const pkg = options.packageName ?? DEFAULT_PKG

  // Never scan the file we're about to (over)write.
  const ignore = [...IGNORE, relative(cwd, outAbs).replace(/\\/g, '/')]
  const discovered = await discoverWithPaths(options.discover ?? DEFAULT_DISCOVER, cwd, ignore)

  const collections: Record<string, Set<string>> = {}
  const globals = new Set<string>()
  const assets = new Set<string>()
  for (const { def } of discovered) {
    if (def.kind === 'assets') for (const k of Object.keys(def.specs)) assets.add(k)
    else if (def.kind === 'global') globals.add(def.slug)
    else if (def.kind === 'collection') {
      collections[def.slug] ??= new Set()
      const set = collections[def.slug]
      for (const rec of def.build(tokens)) set?.add((rec as { _key: string })._key)
    }
  }

  const collectionKeys = Object.fromEntries(Object.entries(collections).map(([slug, set]) => [slug, [...set].sort()]))
  const globalList = [...globals].sort()
  const assetList = [...assets].sort()
  const fromDir = dirname(outAbs)

  const lines: string[] = [
    '/* AUTO-GENERATED by `generateSeedTypes` (payload-seed). Do not edit by hand. */',
    '/* Regenerate after changing any seed `_key`, global, or asset key. */',
    '',
  ]
  if (barrel) {
    lines.push(`import type { SeedDefinition } from '${pkg}'`)
    for (const [i, d] of discovered.entries()) lines.push(`import def${i} from '${importSpecifier(fromDir, d.file)}'`)
    lines.push('')
  }
  lines.push(`declare module '${pkg}' {`, '  interface SeedRegistry {', '    collections: {')
  for (const slug of Object.keys(collectionKeys).sort()) lines.push(`      '${slug}': ${union(collectionKeys[slug] ?? [])}`)
  lines.push('    }', `    globals: ${union(globalList)}`, `    assets: ${union(assetList)}`, '  }', '}', '')
  if (barrel) {
    lines.push(`export const definitions: SeedDefinition[] = [${discovered.map((_, i) => `def${i}`).join(', ')}]`, '')
  }

  await mkdir(fromDir, { recursive: true })
  await writeFile(outAbs, lines.join('\n'), 'utf8')

  return { out: outRel, collections: collectionKeys, globals: globalList, assets: assetList, files: discovered.length }
}
