/* AUTO-GENERATED by `generateSeedTypes` (payload-seed). Do not edit by hand. */
/* Regenerate after changing any seed `_key`, global, or asset key. */

import type { SeedDefinition } from '@pro-laico/payload-seed'
import def0 from './collections/Posts/seed'
import def1 from './collections/Services/seed'
import def2 from './globals/SiteSettings/seed'
import def3 from './seed/assets'

declare module '@pro-laico/payload-seed' {
  interface SeedRegistry {
    collections: {
      'posts': 'launch'
      'services': 'consulting' | 'implementation'
    }
    globals: 'site-settings'
    assets: 'logo' | 'post' | 'serviceA' | 'serviceB'
  }
}

export const definitions: SeedDefinition[] = [def0, def1, def2, def3]
