import { describe, expect, it } from 'vitest'

import { buildTickModel } from '../../src/components/admin/presetManager/tickModel'
import { reachableWidths } from '../../src/lib/prewarm/deriveWidths'
import type { TickConstraints } from '../../src/types'

const constraints: TickConstraints = { dimensionStep: 50, maxDimension: 4096 }
const axis = (docs: Parameters<typeof buildTickModel>[0]['axis']['docs'], totalDocs = docs.length) => ({ docs, totalDocs })

const build = (over: Partial<Parameters<typeof buildTickModel>[0]> = {}) =>
  buildTickModel({ axis: axis([]), presetMatches: null, plan: [], constraints, sourceWidth: 2400, ...over })

describe('buildTickModel', () => {
  it('classifies variants preset vs generated by cacheKey, carrying the preset name', () => {
    const matches = new Map([
      ['og', { variantId: 1, cacheKey: 'og-key' }],
      ['thumbnail', { variantId: 2 }], // no cacheKey — can't classify by it
    ])
    const model = build({
      axis: axis([
        { width: 1200, cacheKey: 'og-key', quality: 80 },
        { width: 640, cacheKey: 'freeform-key', quality: 90 },
      ]),
      presetMatches: matches,
    })
    expect(model.byWidth.get(1200)).toEqual([
      { key: 'og-key', kind: 'preset', width: 1200, height: undefined, fit: undefined, quality: 80, format: undefined, presetName: 'og' },
    ])
    expect(model.byWidth.get(640)?.[0]?.kind).toBe('generated')
  })

  it('gives an off-grid stored width its own position instead of bucketing it', () => {
    const model = build({ axis: axis([{ width: 733, cacheKey: 'k' }]) })
    expect(model.positions).toContain(733)
    expect(reachableWidths(constraints)).not.toContain(733)
    expect(model.byWidth.get(733)).toHaveLength(1)
  })

  it('dedupes planned rows against cached variants by cacheKey, never by width', () => {
    const model = build({
      axis: axis([{ width: 700, cacheKey: 'done' }]),
      plan: [
        { cacheKey: 'done', w: 1000 }, // cached (its render clamped to 700) — no planned tick
        { cacheKey: 'pending', w: 700 }, // not cached — planned, stacking beside the 700 variant
      ],
    })
    const at700 = model.byWidth.get(700) ?? []
    expect(at700.map((e) => e.kind)).toEqual(['generated', 'planned'])
    expect(model.byWidth.get(1000)).toBeUndefined()
  })

  it('stacks multiple renders at one width in a deterministic preset → generated → planned order', () => {
    const matches = new Map([['og', { cacheKey: 'p' }]])
    const model = build({
      axis: axis([
        { width: 500, cacheKey: 'g2', quality: 90 },
        { width: 500, cacheKey: 'p', quality: 80 },
        { width: 500, cacheKey: 'g1', quality: 60 },
      ]),
      presetMatches: matches,
      plan: [{ cacheKey: 'pl', w: 500 }],
    })
    expect((model.byWidth.get(500) ?? []).map((e) => `${e.kind}:${e.quality ?? ''}`)).toEqual([
      'preset:80',
      'generated:60',
      'generated:90',
      'planned:',
    ])
  })

  it('positions are the reachable set unioned with actual widths, ascending', () => {
    const model = build({
      axis: axis([
        { width: 733, cacheKey: 'a' },
        { width: 50, cacheKey: 'b' },
      ]),
    })
    expect(model.positions).toEqual([...new Set([...reachableWidths(constraints), 733])].sort((a, b) => a - b))
  })

  it('flags overflow when the axis fetch was capped', () => {
    expect(build({ axis: axis([{ width: 100 }], 1200) }).overflow).toBe(true)
    expect(build({ axis: axis([{ width: 100 }]) }).overflow).toBe(false)
  })
})
