/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    images: Image;
    'generated-images': GeneratedImage;
    'image-render-profiles': ImageRenderProfile;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    images: {
      variants: 'generated-images';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    'generated-images': GeneratedImagesSelect<false> | GeneratedImagesSelect<true>;
    'image-render-profiles': ImageRenderProfilesSelect<false> | ImageRenderProfilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      imagesPrewarm: TaskImagesPrewarm;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  heroImage?: (number | null) | Image;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload images here. Display sizes are generated on demand and cached — store the original once, render any size.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  variants?: {
    docs?: (number | GeneratedImage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * The render aspect ratio: the ratio the read declared (context.image.aspectRatio), else the natural one.
   */
  aspectRatio?: number | null;
  /**
   * Cache-busting version token for transform URLs (changes on file replace / focal / hotspot edits).
   */
  variantVersion?: string | null;
  /**
   * Optimized URL (≤1280px) for a plain <img> or OG tag, honoring the declared render.
   */
  src?: string | null;
  /**
   * Responsive srcset up to the source width, honoring the declared render (else the natural ratio).
   */
  srcset?: string | null;
  /**
   * Tiny low-quality placeholder (LQIP) for a blur-up / CSS background.
   */
  placeholderURL?: string | null;
  blurHashXs?: string | null;
  blurHashSm?: string | null;
  blurHashMd?: string | null;
  blurHashLg?: string | null;
  blurHashXl?: string | null;
  placeholderXxl?: string | null;
  placeholderX3?: string | null;
  /**
   * Placeholder for the read — opt-in: a finished data URI focal-cropped to the declared render, returned only when the read declares a blur (context.blur = { quality, format } or an X-Blurhash header); null otherwise so undeclared reads carry no data-URI weight.
   */
  placeholder?: string | null;
  /**
   * Color palette extracted at upload: dominant/vibrant/muted (+ dark/light variants), each { background, foreground, title, population }.
   */
  palette?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The file carries an alpha channel.
   */
  hasAlpha?: boolean | null;
  /**
   * No pixel is actually transparent (sampled).
   */
  isOpaque?: boolean | null;
  /**
   * Hotspot circle diameter, % of the crop region’s shorter side. 100 = maximal window (no zoom).
   */
  focalSize?: number | null;
  /**
   * Non-destructive edge trim, % of the image removed from the left.
   */
  cropLeft?: number | null;
  /**
   * Non-destructive edge trim, % removed from the top.
   */
  cropTop?: number | null;
  /**
   * Non-destructive edge trim, % removed from the right.
   */
  cropRight?: number | null;
  /**
   * Non-destructive edge trim, % removed from the bottom.
   */
  cropBottom?: number | null;
  /**
   * Guaranteed public variants for this image (OG, social, fixed sizes). Always generatable and pre-generated on upload; served via /api/img/:id?preset=<name>. Managed by the Presets panel.
   */
  presets?:
    | {
        /**
         * Name of a plugin preset template to apply (leave blank for a custom preset).
         */
        template?: string | null;
        /**
         * Name for a custom preset (used when no template is chosen).
         */
        name?: string | null;
        width?: number | null;
        height?: number | null;
        /**
         * e.g. 16:9
         */
        aspectRatio?: string | null;
        fit?: ('cover' | 'contain' | 'inside' | 'outside' | 'fill') | null;
        quality?: number | null;
        format?: ('avif' | 'webp' | 'jpeg' | 'png') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Max cached variants for this image before new sizes are served from a nearby existing one instead of being generated + stored. Blank uses the project default. Presets never count against this.
   */
  variantLimit?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  /**
   * Small focal-cropped square (160px) for cards, lists, and feeds.
   */
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-images".
 */
export interface GeneratedImage {
  id: number;
  source: number | Image;
  cacheKey: string;
  fit?: string | null;
  format?: string | null;
  quality?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-render-profiles".
 */
export interface ImageRenderProfile {
  id: number;
  /**
   * Canonical render shape: ratio|fit|quality|format. One doc per distinct shape the transform endpoint has served.
   */
  profileKey: string;
  ratio: string;
  fit: string;
  quality: number;
  format: string;
  /**
   * Approximate total serves (flushed from per-process buffers, throttled).
   */
  hitCount?: number | null;
  lastSeenAt?: string | null;
  /**
   * Per-width observation histogram: { "640": { n, last } }. Capped; the least-requested widths are evicted.
   */
  widths?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'imagesPrewarm';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'imagesPrewarm') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'images';
        value: number | Image;
      } | null)
    | ({
        relationTo: 'generated-images';
        value: number | GeneratedImage;
      } | null)
    | ({
        relationTo: 'image-render-profiles';
        value: number | ImageRenderProfile;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt?: T;
  variants?: T;
  aspectRatio?: T;
  variantVersion?: T;
  src?: T;
  srcset?: T;
  placeholderURL?: T;
  blurHashXs?: T;
  blurHashSm?: T;
  blurHashMd?: T;
  blurHashLg?: T;
  blurHashXl?: T;
  placeholderXxl?: T;
  placeholderX3?: T;
  placeholder?: T;
  palette?: T;
  hasAlpha?: T;
  isOpaque?: T;
  focalSize?: T;
  cropLeft?: T;
  cropTop?: T;
  cropRight?: T;
  cropBottom?: T;
  presets?:
    | T
    | {
        template?: T;
        name?: T;
        width?: T;
        height?: T;
        aspectRatio?: T;
        fit?: T;
        quality?: T;
        format?: T;
        id?: T;
      };
  variantLimit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-images_select".
 */
export interface GeneratedImagesSelect<T extends boolean = true> {
  source?: T;
  cacheKey?: T;
  fit?: T;
  format?: T;
  quality?: T;
  focalX?: T;
  focalY?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-render-profiles_select".
 */
export interface ImageRenderProfilesSelect<T extends boolean = true> {
  profileKey?: T;
  ratio?: T;
  fit?: T;
  quality?: T;
  format?: T;
  hitCount?: T;
  lastSeenAt?: T;
  widths?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskImagesPrewarm".
 */
export interface TaskImagesPrewarm {
  input: {
    sourceId: string;
    reason: 'create' | 'replace' | 'focal' | 'manual';
  };
  output: {
    targets?: number | null;
    generated?: number | null;
    failed?: number | null;
    skipped?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module '@pro-laico/payload-seed' {
  interface SeedRegistry {
    collections: {
      'images': 'apple' | 'balloon' | 'lighthouse'
      'pages': 'home'
    }
    globals: never
  }
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}