import { imagesPlugin } from '@pro-laico/payload-images'
import { seedPlugin } from '@pro-laico/payload-seed'
import type { Plugin } from 'payload'
import images from '../seed/images'
import pages from '../seed/pages'

export const plugins: Plugin[] = [
  // prewarm: learn served render profiles off the transform endpoint; new/changed images get
  // their expected variants pre-generated by the imagesPrewarm job (run via payload.jobs.run / CLI).
  imagesPlugin({ prewarm: true }),
  seedPlugin({
    adminButton: true,
    definitions: [images, pages],
    assetsDir: 'seed-assets',
  }),
]
