// DO NOT EDIT MANUALLY. THIS FILE IS AUTOMATICALLY GENERATED.
import localFont from 'next/font/local'

const fontSans = localFont({ src: [{ path: '../../public/fonts/sans-100-900-italic.woff2', weight: '100 900', style: 'italic' }, { path: '../../public/fonts/sans-100-900.woff2', weight: '100 900', style: 'normal' }], variable: '--font-setSans' })
const fontSerif = localFont({ src: [{ path: '../../public/fonts/serif-700-italic.woff2', weight: '700', style: 'italic' }, { path: '../../public/fonts/serif-700.woff2', weight: '700', style: 'normal' }, { path: '../../public/fonts/serif-400-italic.woff2', weight: '400', style: 'italic' }, { path: '../../public/fonts/serif-400.woff2', weight: '400', style: 'normal' }], variable: '--font-setSerif' })
const fontMono = localFont({ src: [{ path: '../../public/fonts/mono-700-italic.woff2', weight: '700', style: 'italic' }, { path: '../../public/fonts/mono-700.woff2', weight: '700', style: 'normal' }, { path: '../../public/fonts/mono-400-italic.woff2', weight: '400', style: 'italic' }, { path: '../../public/fonts/mono-400.woff2', weight: '400', style: 'normal' }], variable: '--font-setMono' })
const fontDisplay = localFont({ src: [{ path: '../../public/fonts/display-300-1000.woff2', weight: '300 1000', style: 'normal' }, { path: '../../public/fonts/display-300-1000-italic.woff2', weight: '300 1000', style: 'oblique 15deg' }], variable: '--font-setDisplay' })

const fonts = { fontSans, fontSerif, fontMono, fontDisplay }
export default fonts
