import fs from 'node:fs'
import path from 'node:path'

import dotenv from 'dotenv'

import type { ExportFontsResponse, Family, RunDownloadFontsOptions, WeightFile } from '../types'
import { familyExportName, familyVarSuffix } from '../lib/families'

const colors = {
  blue: (t: string) => `\x1b[34m${t}\x1b[0m`,
  green: (t: string) => `\x1b[32m${t}\x1b[0m`,
  red: (t: string) => `\x1b[31m${t}\x1b[0m`,
  orange: (t: string) => `\x1b[33m${t}\x1b[0m`,
}

/** Connection-refused / unreachable host — the DESIGNED `predev` state (server not up yet), never
 *  an error. Node buries the code under `cause` (often an AggregateError), so walk the chain. */
const DOWN_CODES = /ECONNREFUSED|ENOTFOUND|EHOSTUNREACH/
const isServerDown = (err: unknown): boolean => {
  if (!err || typeof err !== 'object') return false
  const { code, message, cause, errors } = err as { code?: string; message?: string; cause?: unknown; errors?: unknown[] }
  if (DOWN_CODES.test(code ?? '') || DOWN_CODES.test(message ?? '')) return true
  return isServerDown(cause) || (Array.isArray(errors) && errors.some(isServerDown))
}

function resolveOptions(overrides?: RunDownloadFontsOptions) {
  // An explicit env file (option or PAYLOAD_FONTS_ENV_FILE) is loaded alone; otherwise follow the
  // Next convention — `.env.local` first so its values win over `.env` (dotenv keeps the first).
  const explicitEnvFile = overrides?.envFile ?? process.env.PAYLOAD_FONTS_ENV_FILE
  return {
    fontsOutputDir: overrides?.fontsOutputDir ?? process.env.PAYLOAD_FONTS_OUTPUT_DIR ?? './public/fonts',
    definitionFile: overrides?.definitionFile ?? process.env.PAYLOAD_FONTS_DEFINITION_FILE ?? './src/app/definition.ts',
    envFiles: explicitEnvFile ? [explicitEnvFile] : ['./.env.local', './.env'],
    localFontSrcPrefix: overrides?.localFontSrcPrefix ?? process.env.PAYLOAD_FONTS_SRC_PREFIX ?? '../../public/fonts',
    cssVariablePrefix: overrides?.cssVariablePrefix ?? process.env.PAYLOAD_FONTS_CSS_VAR_PREFIX ?? '--font-set',
    endpointPath: overrides?.endpointPath ?? process.env.PAYLOAD_FONTS_ENDPOINT ?? '/api/fonts/export',
    verbose: overrides?.verbose ?? process.env.PAYLOAD_FONTS_VERBOSE === 'true',
  }
}

export async function runDownloadFonts(overrides?: RunDownloadFontsOptions): Promise<void> {
  const opts = resolveOptions(overrides)
  dotenv.config({ path: opts.envFiles, quiet: true })

  const FONT_FILES_DIR = opts.fontsOutputDir
  const FONT_DEFINITION_FILE = opts.definitionFile
  const localPrefix = opts.localFontSrcPrefix.replace(/\/$/, '')

  function generateFontDefinitions(familyFiles: Record<Family, WeightFile[]>): void {
    // One `localFont()` per family with files, each with an array of weighted `src` entries — so
    // multiple weights collapse into a single CSS variable for that family. The export name +
    // variable are derived from the family key by the shared convention (`sans` → `fontSans` /
    // `<prefix>Sans`).
    const configs = Object.entries(familyFiles)
      .filter(([, files]) => files.length > 0)
      .map(([family, files]) => ({ name: familyExportName(family), files, variable: `${opts.cssVariablePrefix}${familyVarSuffix(family)}` }))

    const declarations = configs
      .map((c) => {
        const src = c.files.map((f) => `{ path: '${f.path}', weight: '${f.weight}', style: '${f.style}' }`).join(', ')
        return `const ${c.name} = localFont({ src: [${src}], variable: '${c.variable}' })`
      })
      .join('\n')
    const exports = configs.map((c) => c.name).join(', ')

    fs.mkdirSync(path.dirname(FONT_DEFINITION_FILE), { recursive: true })

    // No-fonts stub omits the `localFont` import entirely so the generated file
    // passes any consumer's unused-import lint (eslint or Biome) as-is.
    fs.writeFileSync(
      FONT_DEFINITION_FILE,
      configs.length === 0
        ? `// DO NOT EDIT MANUALLY. THIS FILE IS AUTOMATICALLY GENERATED.

// No fonts available

const fonts = {}
export default fonts
`
        : `// DO NOT EDIT MANUALLY. THIS FILE IS AUTOMATICALLY GENERATED.
import localFont from 'next/font/local'

${declarations}

const fonts = { ${exports} }
export default fonts
`,
    )
  }

  /**
   * Reset the generated module to an empty-but-valid stub. Called on EVERY error / skip path so a
   * failed or partial run never leaves a `definition.ts` that imports font files which aren't on
   * disk — a gitignored `public/fonts/` on a fresh checkout, or a dir wiped mid-run — which would
   * break `next build` with "Can't resolve". It ALWAYS overwrites: a stale definition surviving a
   * failure is the bug we're fixing (the atomic version only wrote this stub when the file was
   * absent), so a definition is never preserved on error.
   */
  function writeEmptyDefinitions(): void {
    generateFontDefinitions({})
  }

  function wipeFontFiles(): void {
    if (!fs.existsSync(FONT_FILES_DIR)) fs.mkdirSync(FONT_FILES_DIR, { recursive: true })
    // Only unlink files — a stray subdirectory would make unlinkSync throw EISDIR.
    for (const file of fs.readdirSync(FONT_FILES_DIR)) {
      const filePath = path.join(FONT_FILES_DIR, file)
      if (fs.statSync(filePath).isFile()) fs.unlinkSync(filePath)
    }
  }

  /** Report a failure and reset the definition to empty, so the build still compiles. */
  function warnAndEmpty(message: string, error?: unknown): void {
    console.warn(colors.red(message))
    if (error) {
      if (opts.verbose) console.warn(error)
      else console.warn(colors.orange('Re-run with --verbose (or set PAYLOAD_FONTS_VERBOSE=true) to see the full error.'))
    }
    console.warn(colors.orange('Font download failed — wrote an empty definition so the build can proceed.'))
    writeEmptyDefinitions()
  }

  // Any failure anywhere in the run resets the definition to empty (via warnAndEmpty on the
  // handled paths, and the catch below for anything unexpected).
  try {
    console.log(colors.blue('Starting Font Download...\n'))

    const siteUrl = overrides?.siteUrl ?? process.env.FONT_DOWNLOAD_URL
    const secret = process.env.PAYLOAD_SECRET
    if (!siteUrl || !secret) {
      const searched = ` (searched ${opts.envFiles.join(', ')})`
      if (!siteUrl) console.warn(colors.red(`Missing required environment variable: FONT_DOWNLOAD_URL${searched}`))
      if (!secret) console.warn(colors.red(`Missing required environment variable: PAYLOAD_SECRET${searched}`))
      console.warn(colors.orange('Font download skipped — wrote an empty definition so the build can proceed.'))
      writeEmptyDefinitions()
      return
    }
    if (!/^https?:\/\//i.test(siteUrl) || !URL.canParse(siteUrl)) {
      warnAndEmpty(`FONT_DOWNLOAD_URL is not a valid http(s) URL: "${siteUrl}" — expected e.g. http://localhost:3000`)
      return
    }

    // Fetch the active fonts from the plugin's export endpoint, authenticating with the project's
    // PAYLOAD_SECRET.
    const endpoint = new URL(opts.endpointPath, siteUrl).toString()
    let manifest: ExportFontsResponse
    try {
      const res = await fetch(endpoint, { headers: { Authorization: `Bearer ${secret}` } })
      if (!res.ok) {
        const hint =
          res.status === 401 || res.status === 403
            ? " — your local PAYLOAD_SECRET doesn't match the server's"
            : res.status === 404
              ? ' — is the fonts plugin registered on that app? (or set PAYLOAD_FONTS_ENDPOINT)'
              : ''
        warnAndEmpty(`Font export endpoint returned HTTP ${res.status} ${res.statusText}${hint}`)
        return
      }
      manifest = (await res.json()) as ExportFontsResponse
    } catch (err) {
      if (isServerDown(err)) {
        // The DESIGNED predev state: `predev` runs before the dev server exists. Not an error.
        console.log(`[payload-fonts] no running Payload at ${endpoint} — wrote the empty dev stub (DevFonts serves fonts at runtime in dev).`)
        writeEmptyDefinitions()
        return
      }
      warnAndEmpty(`Could not reach the font export endpoint at ${endpoint}`, err)
      return
    }

    const fonts = manifest?.fonts ?? {}

    wipeFontFiles()

    // Discover the active families from the response keys (the plugin's `families` option drives them).
    const families: Family[] = Object.keys(fonts)
    const familyFiles: Record<Family, WeightFile[]> = {}
    let count = 0
    for (const family of families) {
      const bucket: WeightFile[] = []
      familyFiles[family] = bucket
      const files = fonts[family]
      if (!files) continue
      for (let i = 0; i < files.length; i++) {
        const font = files[i]
        if (!font?.data) continue
        try {
          const ext = font.extension || font.filename.split('.').pop()?.toLowerCase() || 'woff2'
          const weight = font.weight || '400'
          const isItalic = font.style === 'italic'
          // A slnt-axis italic declares `oblique <angle>` so the browser drives the axis; a true
          // italic (explicit file or ital axis) declares plain `italic`.
          const style = isItalic && font.obliqueAngle ? `oblique ${font.obliqueAngle}deg` : font.style || 'normal'
          // A variable font's weight is a "min max" range; collapse the space for a filename-safe
          // slug (sans-100-900). The emitted `weight` below keeps the range.
          const weightSlug = weight.replace(/\s+/g, '-')
          // Distinct filename per weight/style; append the index if two files share one.
          const base = `${family}-${weightSlug}${isItalic ? '-italic' : ''}`
          const fileName = bucket.some((f) => f.path.endsWith(`/${base}.${ext}`)) ? `${base}-${i}` : base
          fs.writeFileSync(path.join(FONT_FILES_DIR, `${fileName}.${ext}`), Buffer.from(font.data, 'base64'))
          bucket.push({ path: `${localPrefix}/${fileName}.${ext}`, weight, style })
          count++
        } catch (err) {
          console.warn(colors.red(`Failed to write ${family} font (weight ${font.weight ?? '?'})`))
          if (opts.verbose) console.warn(err)
        }
      }
      if (bucket.length)
        console.log(`${colors.green('✓')} Downloaded ${family} font (${bucket.length} weight${bucket.length === 1 ? '' : 's'})`)
    }

    generateFontDefinitions(familyFiles)

    if (count === 0) {
      console.log(colors.orange('\nNo active fonts returned — generated an empty definition.'))
      // Newer servers say WHY each family came back empty (older ones omit `diagnostics`).
      for (const [family, d] of Object.entries(manifest?.diagnostics ?? {})) {
        if (!d) continue
        const name = d.typeface ? `'${d.typeface}'` : 'a typeface'
        if (!d.selected) console.log(colors.orange(`  ${family}: no typeface selected in the fontSet global`))
        else if (d.optimizedFiles === 0)
          console.log(
            colors.orange(
              `  ${family}: ${name} selected but has 0 optimized files — did the subsetter run on the server? (Next.js: serverExternalPackages: ['subset-font', 'harfbuzzjs', 'fontkit'])`,
            ),
          )
        else if (d.readFailures > 0)
          console.log(
            colors.orange(
              `  ${family}: ${name} selected but ${d.readFailures}/${d.optimizedFiles} optimized files could not be read from storage`,
            ),
          )
      }
      console.log('')
    } else console.log(colors.green(`\n✓ Font definitions generated (${count} font file${count === 1 ? '' : 's'})\n`))
  } catch (err) {
    // Any unexpected failure → empty definition, so a broken run never leaves a stale one that
    // imports font files that aren't on disk (the bug this guards against).
    warnAndEmpty('Unexpected error during font download', err)
  }
}
