/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GenericFontFamily".
 */
export type GenericFontFamily = 'sans' | 'serif' | 'mono' | 'display';
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    projects: Project;
    team: Team;
    testimonials: Testimonial;
    images: Image;
    'generated-images': GeneratedImage;
    icon: Icon;
    iconSet: IconSet;
    iconRequest: IconRequest;
    'mux-video': MuxVideo;
    font: Font;
    fontOriginal: FontOriginal;
    fontOptimized: FontOptimized;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    images: {
      variants: 'generated-images';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'images';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    'generated-images': GeneratedImagesSelect<false> | GeneratedImagesSelect<true>;
    icon: IconSelect<false> | IconSelect<true>;
    iconSet: IconSetSelect<false> | IconSetSelect<true>;
    iconRequest: IconRequestSelect<false> | IconRequestSelect<true>;
    'mux-video': MuxVideoSelect<false> | MuxVideoSelect<true>;
    font: FontSelect<false> | FontSelect<true>;
    fontOriginal: FontOriginalSelect<false> | FontOriginalSelect<true>;
    fontOptimized: FontOptimizedSelect<false> | FontOptimizedSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    fontSet: FontSet;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    fontSet: FontSetSelect<false> | FontSetSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  icon?: (number | null) | Icon;
  image?: (number | null) | Image;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icon".
 */
export interface Icon {
  id: number;
  optimized?: string | null;
  svgString?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Upload images here. Display sizes are generated on demand and cached — store the original once, render any size.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  variants?: {
    docs?: (number | GeneratedImage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * The render aspect ratio: the ratio the read declared (context.image.aspectRatio), else the natural one.
   */
  aspectRatio?: number | null;
  /**
   * Cache-busting version token for transform URLs (changes on file replace / focal / hotspot edits).
   */
  variantVersion?: string | null;
  /**
   * Optimized URL (≤1280px) for a plain <img> or OG tag, honoring the declared render.
   */
  src?: string | null;
  /**
   * Responsive srcset up to the source width, honoring the declared render (else the natural ratio).
   */
  srcset?: string | null;
  /**
   * Tiny low-quality placeholder (LQIP) for a blur-up / CSS background.
   */
  placeholderURL?: string | null;
  blurHashXs?: string | null;
  blurHashSm?: string | null;
  blurHashMd?: string | null;
  blurHashLg?: string | null;
  blurHashXl?: string | null;
  placeholderXxl?: string | null;
  placeholderX3?: string | null;
  /**
   * Placeholder for the read: a finished data URI focal-cropped to the declared render (context.image.aspectRatio + context.blur = { quality, format }, or an X-Blurhash header); the raw sm-tier hash when nothing is declared.
   */
  croppedBlurHash?: string | null;
  /**
   * Color palette extracted at upload: dominant/vibrant/muted (+ dark/light variants), each { background, foreground, title, population }.
   */
  palette?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The file carries an alpha channel.
   */
  hasAlpha?: boolean | null;
  /**
   * No pixel is actually transparent (sampled).
   */
  isOpaque?: boolean | null;
  /**
   * Hotspot circle diameter, % of the crop region’s shorter side. 100 = maximal window (no zoom).
   */
  focalSize?: number | null;
  /**
   * Non-destructive edge trim, % of the image removed from the left.
   */
  cropLeft?: number | null;
  /**
   * Non-destructive edge trim, % removed from the top.
   */
  cropTop?: number | null;
  /**
   * Non-destructive edge trim, % removed from the right.
   */
  cropRight?: number | null;
  /**
   * Non-destructive edge trim, % removed from the bottom.
   */
  cropBottom?: number | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  /**
   * Small focal-cropped square (160px) for cards, lists, and feeds.
   */
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-images".
 */
export interface GeneratedImage {
  id: number;
  source: number | Image;
  cacheKey: string;
  fit?: string | null;
  format?: string | null;
  quality?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'images';
          value: number | Image;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'images'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  client?: string | null;
  location?: string | null;
  year?: number | null;
  summary?: string | null;
  description?: string | null;
  coverImage?: (number | null) | Image;
  gallery?:
    | {
        image: number | Image;
        id?: string | null;
      }[]
    | null;
  video?: (number | null) | MuxVideo;
  services?: (number | Service)[] | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mux-video".
 */
export interface MuxVideo {
  id: number;
  source?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * A unique title for this video that will help you identify it later.
   */
  title: string;
  assetId?: string | null;
  status?: ('preparing' | 'ready' | 'errored') | null;
  error?: string | null;
  duration?: number | null;
  /**
   * A timestamp (in seconds) from the video to be used as the poster image. When unset, defaults to the middle of the video.
   */
  posterTimestamp?: number | null;
  aspectRatio?: string | null;
  maxWidth?: number | null;
  maxHeight?: number | null;
  playbackOptions?:
    | {
        playbackId: string;
        playbackPolicy: 'signed' | 'public';
        playbackUrl?: string | null;
        posterUrl?: string | null;
        gifUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Image;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  company?: string | null;
  project?: (number | null) | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iconSet".
 */
export interface IconSet {
  id: number;
  /**
   * Render this set across the frontend. Activating a set deactivates the others.
   */
  active?: boolean | null;
  title: string;
  iconsArray?:
    | {
        /**
         * The name the frontend looks the icon up by (auto kebab-cased).
         */
        name: string;
        /**
         * Select an icon.
         */
        icon?: (number | null) | Icon;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Icon names requested at runtime that did not resolve to an icon in the active set. Populated when iconsPlugin({ trackRequests: true }) is set; compare against the IconSet usage panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iconRequest".
 */
export interface IconRequest {
  id: number;
  name: string;
  count?: number | null;
  firstRequestedAt?: string | null;
  lastRequestedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload typefaces here to add them to your library. Uploading alone doesn’t put a font on your site — activate it by picking it in Font Set.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font".
 */
export interface Font {
  id: number;
  title: string;
  family: GenericFontFamily;
  /**
   * Web-ready files generated from your uploads. 0 means nothing was served yet — re-save; if it stays 0, the upload may have failed to optimize (check server logs).
   */
  servedFiles?: number | null;
  /**
   * One file covering many weights. Use this OR specific weights below — not both.
   */
  variable?: {
    upright?: (number | null) | FontOriginal;
    italic?: (number | null) | FontOriginal;
  };
  /**
   * One file per weight/style. Add only the weights you need.
   */
  weights?:
    | {
        weight: '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900';
        style: 'normal' | 'italic';
        file: number | FontOriginal;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fontOriginal".
 */
export interface FontOriginal {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fontOptimized".
 */
export interface FontOptimized {
  id: number;
  font?: (number | null) | Font;
  original?: (number | null) | FontOriginal;
  weight?: string | null;
  style?: ('normal' | 'italic') | null;
  isVariable?: boolean | null;
  italCapable?: boolean | null;
  obliqueAngle?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'images';
        value: number | Image;
      } | null)
    | ({
        relationTo: 'generated-images';
        value: number | GeneratedImage;
      } | null)
    | ({
        relationTo: 'icon';
        value: number | Icon;
      } | null)
    | ({
        relationTo: 'iconSet';
        value: number | IconSet;
      } | null)
    | ({
        relationTo: 'iconRequest';
        value: number | IconRequest;
      } | null)
    | ({
        relationTo: 'mux-video';
        value: number | MuxVideo;
      } | null)
    | ({
        relationTo: 'font';
        value: number | Font;
      } | null)
    | ({
        relationTo: 'fontOriginal';
        value: number | FontOriginal;
      } | null)
    | ({
        relationTo: 'fontOptimized';
        value: number | FontOptimized;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  location?: T;
  year?: T;
  summary?: T;
  description?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  video?: T;
  services?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  company?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt?: T;
  variants?: T;
  aspectRatio?: T;
  variantVersion?: T;
  src?: T;
  srcset?: T;
  placeholderURL?: T;
  blurHashXs?: T;
  blurHashSm?: T;
  blurHashMd?: T;
  blurHashLg?: T;
  blurHashXl?: T;
  placeholderXxl?: T;
  placeholderX3?: T;
  croppedBlurHash?: T;
  palette?: T;
  hasAlpha?: T;
  isOpaque?: T;
  focalSize?: T;
  cropLeft?: T;
  cropTop?: T;
  cropRight?: T;
  cropBottom?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-images_select".
 */
export interface GeneratedImagesSelect<T extends boolean = true> {
  source?: T;
  cacheKey?: T;
  fit?: T;
  format?: T;
  quality?: T;
  focalX?: T;
  focalY?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icon_select".
 */
export interface IconSelect<T extends boolean = true> {
  optimized?: T;
  svgString?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iconSet_select".
 */
export interface IconSetSelect<T extends boolean = true> {
  active?: T;
  title?: T;
  iconsArray?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iconRequest_select".
 */
export interface IconRequestSelect<T extends boolean = true> {
  name?: T;
  count?: T;
  firstRequestedAt?: T;
  lastRequestedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mux-video_select".
 */
export interface MuxVideoSelect<T extends boolean = true> {
  source?: T;
  title?: T;
  assetId?: T;
  status?: T;
  error?: T;
  duration?: T;
  posterTimestamp?: T;
  aspectRatio?: T;
  maxWidth?: T;
  maxHeight?: T;
  playbackOptions?:
    | T
    | {
        playbackId?: T;
        playbackPolicy?: T;
        playbackUrl?: T;
        posterUrl?: T;
        gifUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font_select".
 */
export interface FontSelect<T extends boolean = true> {
  title?: T;
  family?: T;
  servedFiles?: T;
  variable?:
    | T
    | {
        upright?: T;
        italic?: T;
      };
  weights?:
    | T
    | {
        weight?: T;
        style?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fontOriginal_select".
 */
export interface FontOriginalSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fontOptimized_select".
 */
export interface FontOptimizedSelect<T extends boolean = true> {
  font?: T;
  original?: T;
  weight?: T;
  style?: T;
  isVariable?: T;
  italCapable?: T;
  obliqueAngle?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  tagline?: string | null;
  description?: string | null;
  heroImage?: (number | null) | Image;
  showreel?: (number | null) | MuxVideo;
  featuredProject?: (number | null) | Project;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Choose which uploaded typeface fills each slot. This is what actually puts a font on your site — upload in Font first, then activate it here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fontSet".
 */
export interface FontSet {
  id: number;
  sans?: (number | null) | Font;
  serif?: (number | null) | Font;
  mono?: (number | null) | Font;
  display?: (number | null) | Font;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  description?: T;
  heroImage?: T;
  showreel?: T;
  featuredProject?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fontSet_select".
 */
export interface FontSetSelect<T extends boolean = true> {
  sans?: T;
  serif?: T;
  mono?: T;
  display?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'iconSet';
      value: number | IconSet;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module '@pro-laico/payload-seed' {
  interface SeedRegistry {
    collections: {
      'font': 'inter' | 'jetbrains-mono' | 'lora' | 'recursive'
      'fontOriginal': 'inter-variable' | 'inter-variable-italic' | 'jetbrains-mono' | 'jetbrains-mono-700' | 'jetbrains-mono-700-italic' | 'jetbrains-mono-italic' | 'lora' | 'lora-700' | 'lora-700-italic' | 'lora-italic' | 'recursive-variable'
      'icon': 'architecture' | 'architecture-alt' | 'arrow-right' | 'arrow-right-alt' | 'check' | 'check-alt' | 'interiors' | 'interiors-alt' | 'landscape' | 'landscape-alt' | 'mail' | 'mail-alt' | 'map-pin' | 'map-pin-alt' | 'phone' | 'phone-alt' | 'renovation' | 'renovation-alt' | 'sparkles' | 'sparkles-alt'
      'iconSet': 'alternate' | 'default'
      'images': 'cedar-hill' | 'cedar-hill-interior' | 'foundry-detail' | 'foundry-loft' | 'hero' | 'riverside-interior' | 'riverside-pavilion' | 'svc-architecture' | 'svc-interiors' | 'svc-landscape' | 'svc-renovation' | 'team-1' | 'team-2' | 'team-3'
      'mux-video': 'showreel'
      'payload-folders': 'projects' | 'services' | 'site' | 'team'
      'projects': 'cedar-hill-residence' | 'foundry-loft' | 'riverside-pavilion'
      'services': 'architecture' | 'interiors' | 'landscape' | 'renovation'
      'team': 'elena' | 'sam' | 'theo'
      'testimonials': 'cedar-hill' | 'foundry' | 'riverside'
    }
    globals: 'fontSet' | 'site-settings'
  }
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}