// Generated by `payload-fonts-download` (the `prebuild` / `generate:fonts` scripts). This empty
// baseline is committed so `import @/app/definition` resolves in dev + CI without a build step; a
// production build overwrites it with the active fonts. In dev the empty definition lets
// `<DevFonts />` load fonts from Payload at runtime instead (see src/app/(frontend)/layout.tsx).
const fonts = {}
export default fonts
